### ISSUE TITLE
npm install failing

### ISSUE THREAD

**Issue by vasa-develop** [byteball/email-attestation#9]
**Platform:**
Linux 16.04 LTS

**npm version**
6.1.0

**node version**
v9.5.0

**Description**
I cloned the repo and tried ```sudo npm install```

**Output**
> sqlite3@3.1.4 install /home/vasa/Desktop/ByteBall/email-attestation/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ '/usr/local/bin/node',
node-pre-gyp verb cli   '/home/vasa/Desktop/ByteBall/email-attestation/node_modules/sqlite3/node_modules/.bin/node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@0.6.28
node-pre-gyp info using node@9.5.0 | linux | x64
node-pre-gyp verb command install []
node-pre-gyp info check checked for "/home/vasa/Desktop/ByteBall/email-attestation/node_modules/sqlite3/lib/binding/node-v59-linux-x64/node_sqlite3.node" (not found)
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.4/node-v59-linux-x64.tar.gz
node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.4/node-v59-linux-x64.tar.gz
node-pre-gyp ERR! Tried to download: https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.4/node-v59-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.4 and node@9.5.0 (node-v59 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.4/node-v59-linux-x64.tar.gz 
node-pre-gyp verb command build [ 'rebuild' ]
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/vasa/Desktop/ByteBall/email-attestation/node_modules/sqlite3/build'
gyp ERR! System Linux 4.13.0-45-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/vasa/Desktop/ByteBall/email-attestation/node_modules/sqlite3/lib/binding/node-v59-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/home/vasa/Desktop/ByteBall/email-attestation/node_modules/sqlite3/lib/binding/node-v59-linux-x64"
gyp ERR! cwd /home/vasa/Desktop/ByteBall/email-attestation/node_modules/sqlite3
gyp ERR! node -v v9.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/vasa/Desktop/ByteBall/email-attestation/node_modules/sqlite3/lib/binding/node-v59-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/vasa/Desktop/ByteBall/email-attestation/node_modules/sqlite3/lib/binding/node-v59-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/vasa/Desktop/ByteBall/email-attestation/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:160:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:943:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
node-pre-gyp ERR! System Linux 4.13.0-45-generic
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/vasa/Desktop/ByteBall/email-attestation/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/vasa/Desktop/ByteBall/email-attestation/node_modules/sqlite3
node-pre-gyp ERR! node -v v9.5.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.28
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/vasa/Desktop/ByteBall/email-attestation/node_modules/sqlite3/lib/binding/node-v59-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/vasa/Desktop/ByteBall/email-attestation/node_modules/sqlite3/lib/binding/node-v59-linux-x64' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@3.1.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@3.1.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vasa/.npm/_logs/2018-06-26T14_16_38_603Z-debug.log

**Comments**
Seems like your server https://mapbox-node-binary.s3.amazonaws.com is not public.

**Comment by tarmo888** [comment]
I had same problem with sqlite3 on node 8, but I use `nvm` and there is no problem if you use node 6.
